Add ccache

diff --git a/.github/workflows/build-artifact.yaml b/.github/workflows/build-artifact.yaml
--- a/.github/workflows/build-artifact.yaml
+++ b/.github/workflows/build-artifact.yaml
@@ -307,6 +307,20 @@ jobs:
         shell: bash
 
     steps:
+      - name: Check Redis credentials
+        # Failing internal jobs draws attention immediately so we can fix them and make them fast.
+        # Forks will never have secrets; don't fail the job for them, they'll just run slower
+        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
+        run: |
+          if [ -z "${{ secrets.REDIS_PASSWORD }}" ]; then
+            echo "Redis password is missing. Did you forget 'secrets: inherit'?"
+            exit 1
+          fi
+          # Conditionally set this here so that it remains unset on forks, otherwise it resolves an invalid URL and the job fails
+          CCACHE_REMOTE_STORAGE="redis://${{ vars.REDIS_USER }}:${{ secrets.REDIS_PASSWORD }}@${{ vars.REDIS_HOST }}:${{ vars.REDIS_PORT }}|read-only=${{ vars.REDIS_IS_READONLY }}"
+          echo "CCACHE_REMOTE_STORAGE=${CCACHE_REMOTE_STORAGE}" >> $GITHUB_ENV
+          echo "CCACHE_REMOTE_STORAGE: ${CCACHE_REMOTE_STORAGE}"
+
       - name: ⬇️ Checkout
         uses: actions/checkout@v4
         with:
@@ -332,7 +346,9 @@ jobs:
       - name: 🐍 Build wheel
         uses: pypa/cibuildwheel@v2.23.2
         env:
-          CIBW_ENVIRONMENT: "CIBW_ENABLE_TRACY=${{ env.ENABLE_TRACY_BUILD }}"
+          CIBW_ENVIRONMENT: "CCACHE_REMOTE_ONLY=true CCACHE_TEMPDIR=/tmp/ccache CCACHE_REMOTE_STORAGE=${{ env.CCACHE_REMOTE_STORAGE }} CIBW_ENABLE_TRACY=${{ env.ENABLE_TRACY_BUILD }}"
+          CIBW_BEFORE_BUILD: "mkdir -p /tmp/ccache && ccache -z"
+          CIBW_AFTER_BUILD: "ccache -s"
           CIBW_MANYLINUX_X86_64_IMAGE: harbor.ci.tenstorrent.net/${{ needs.build-docker-image.outputs.manylinux-tag || 'docker-image-unresolved!' }}
 
       - name: Set wheel artifact name
