[skip ci] Grant Merge Gate's ClangTidy scan permission to access Redis (#20309)
### Ticket
None

### Problem description
Merge Gate is not benefiting from ccache. Turns out it didn't get the
password. Minor details.

### What's changed
Give it access to secrets.

diff --git a/.github/workflows/code-analysis.yaml b/.github/workflows/code-analysis.yaml
--- a/.github/workflows/code-analysis.yaml
+++ b/.github/workflows/code-analysis.yaml
@@ -97,6 +97,13 @@ jobs:
           # So we have to do it this way
           echo "CCACHE_READONLY=1" >> "$GITHUB_ENV"
 
+      - name: Check Redis credentials
+        run: |
+          if [ -z "${{ secrets.REDIS_PASSWORD }}" ]; then
+            echo "Redis password is missing. Did you forget 'secrets: inherit'?"
+            exit 1
+          fi
+
       - name: Create ccache tmpdir
         run: |
           mkdir -p /tmp/ccache
