fix. Nightly fixes + coverage report generation script (#1042)
### Problem description
- test_unpack_matmul.py was failing and thus the whole nightly test
suite.
- It wasn't easy to tests just a *.cpp file without passsing any
arguments to constructors of `TestConfig` and `ProfilerConfig`.
- There wasn't a simple way to see coverage data for one are few tests
variants

### What's changed
- Nightly is now passing
- You can write something like `configuration =
ProfilerConfig("sources/profiler_overhead_test.cpp")` and your test
would execute as intended.
- You can execute `./generate_coverage_report.sh` to produce lcov html
report of your coverage test run.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] Documentation update

### Checklist
<!-- These are required steps and need to be run from tt-metal
repository's Actions. Use links below and replace them with your run -->
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
- [ ] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI passes (if applicable)

diff --git a/.github/workflows/setup-and-test.yml b/.github/workflows/setup-and-test.yml
--- a/.github/workflows/setup-and-test.yml
+++ b/.github/workflows/setup-and-test.yml
@@ -105,7 +105,7 @@ jobs:
                 -m "${{ inputs.pytest_markers }}" \
                 ${{ inputs.random_order && '--random-order-bucket=global' || '' }} \
                 --splits $SPLITS --group ${{ matrix.test_group }} \
-                --override-ini="addopts=-v" --tb=short --timeout=60 \
+                --override-ini="addopts=-v" --timeout=60 \
                 --junitxml=pytest-report-${CHIP_ARCH}-${{ matrix.test_group }}-compile.xml .
 
           echo "Running tests"
@@ -113,13 +113,22 @@ jobs:
                 -m "${{ inputs.pytest_markers }}" \
                 ${{ inputs.random_order && '--random-order-bucket=global' || '' }} \
                 --splits $SPLITS --group ${{ matrix.test_group }} \
-                --override-ini="addopts=-v" --tb=short --timeout=60 \
+                --override-ini="addopts=-v" --timeout=60 \
                 --junitxml=pytest-report-${CHIP_ARCH}-${{ matrix.test_group }}-run.xml .
 
-          pip install junitparser
           junitparser merge pytest-report-${CHIP_ARCH}-${{ matrix.test_group }}-compile.xml \
                    pytest-report-${CHIP_ARCH}-${{ matrix.test_group }}-run.xml \
                    pytest-report-${CHIP_ARCH}-${{ matrix.test_group }}.xml
+
+          if [[ "${{ inputs.coverage }}" == "true" ]]; then
+            if [ ! -f "/tmp/tt-llk-build/merged_coverage.info" ]; then
+              echo "Error: Coverage file /tmp/tt-llk-build/merged_coverage.info not found." >&2
+              echo "Ensure coverage artefcats was generated!" >&2
+              exit 1
+            fi
+            cd ../../
+            cp /tmp/tt-llk-build/merged_coverage.info code-coverage-${CHIP_ARCH}-${{ matrix.test_group }}.info
+          fi
 
       # Step 4: Zip performance data if perf tests were run
       - name: Zip performance data
