Revert "[to be reverted] turn on only multi-modal benchmark for QwenVL test case"
This reverts commit 65e7e7fce63d10859b38a1e8b9a93076afb27ad2.

diff --git a/.github/workflows/vllm-nightly-tests-impl.yaml b/.github/workflows/vllm-nightly-tests-impl.yaml
--- a/.github/workflows/vllm-nightly-tests-impl.yaml
+++ b/.github/workflows/vllm-nightly-tests-impl.yaml
@@ -24,19 +24,19 @@ jobs:
       fail-fast: false
       matrix:
         test-group: [
-          # {
-          #   name: "[WH-T3K] Llama-3.1-8B-Instruct",
-          #   model: "meta-llama/Llama-3.1-8B-Instruct",
-          #   server-timeout: 5,
-          #   benchmark-timeout: 5,
-          #   runner-label: config-t3000,
-          #   mesh-device: T3K,
-          #   tt-llama-text-ver: tt_transformers,
-          #   override-tt-config: "{\"fabric_config\": \"FABRIC_1D\"}",
-          #   multimodal: false,
-          #   co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
-          #   co-owner-2-id: U08CEGF78ET, # Salar Hosseini Khorasgani
-          # },
+          {
+            name: "[WH-T3K] Llama-3.1-8B-Instruct",
+            model: "meta-llama/Llama-3.1-8B-Instruct",
+            server-timeout: 5,
+            benchmark-timeout: 5,
+            runner-label: config-t3000,
+            mesh-device: T3K,
+            tt-llama-text-ver: tt_transformers,
+            override-tt-config: "{\"fabric_config\": \"FABRIC_1D\"}",
+            multimodal: false,
+            co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
+            co-owner-2-id: U08CEGF78ET, # Salar Hosseini Khorasgani
+          },
           {
             name: "[WH-T3K] Qwen2.5-VL-72B-Instruct",
             model: "Qwen/Qwen2.5-VL-72B-Instruct",
@@ -49,81 +49,81 @@ jobs:
             multimodal: true,
             co-owner-1-id: U07RY6B5FLJ, # Gongyu Wang
           },
-          # {
-          #   name: "[BH-DB] Llama-3.1-8B-Instruct",
-          #   model: "meta-llama/Llama-3.1-8B-Instruct",
-          #   server-timeout: 5,
-          #   benchmark-timeout: 5,
-          #   runner-label: BH-DeskBox,
-          #   mesh-device: P150x2,
-          #   tt-llama-text-ver: tt_transformers,
-          #   override-tt-config: "{\"data_parallel\": 2}",
-          #   multimodal: false,
-          #   owner_id: U08GELBB1AP, # Ambrose Ling
-          # },
-          # {
-          #   name: "[BH-QB] Llama-3.1-8B-Instruct",
-          #   model: "meta-llama/Llama-3.1-8B-Instruct",
-          #   server-timeout: 5,
-          #   benchmark-timeout: 5,
-          #   runner-label: bh-LLMBox,
-          #   mesh-device: P150x4,
-          #   tt-llama-text-ver: tt_transformers,
-          #   override-tt-config: "{\"data_parallel\": 4}",
-          #   multimodal: false,
-          #   owner_id: U08CEGF78ET, # Salar Hosseini Khorasgani
-          # },
-          # {
-          #   name: "[BH-LB] Llama-3.1-8B-Instruct",
-          #   model: "meta-llama/Llama-3.1-8B-Instruct",
-          #   server-timeout: 35,
-          #   benchmark-timeout: 10,
-          #   runner-label: bh-rackbox,
-          #   mesh-device: P150x8,
-          #   tt-llama-text-ver: tt_transformers,
-          #   override-tt-config: "{\"data_parallel\": 8}",
-          #   multimodal: false,
-          #   owner_id: U08GELBB1AP, # Ambrose Ling
-          # },
-          # {
-          #   name: "[WH-GLX] Llama-3.3-70B-Instruct",
-          #   model: "meta-llama/Llama-3.3-70B-Instruct",
-          #   server-timeout: 35,
-          #   benchmark-timeout: 10,
-          #   runner-label: topology-6u,
-          #   mesh-device: TG,
-          #   tt-llama-text-ver: llama3_70b_galaxy,
-          #   override-tt-config: "{\"dispatch_core_axis\": \"col\", \"sample_on_device_mode\": \"all\", \"fabric_config\": \"FABRIC_1D_RING\", \"worker_l1_size\": 1344544, \"trace_region_size\": 95693824}",
-          #   multimodal: false,
-          #   co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
-          #   co-owner-2-id: U08CEGF78ET, # Salar Hosseini Khorasgani
-          # },
-          # {
-          #   name: "[WH-GLX] Llama-8B DP=16",
-          #   model: "meta-llama/Llama-3.1-8B-Instruct",
-          #   server-timeout: 10,
-          #   benchmark-timeout: 5,
-          #   runner-label: topology-6u,
-          #   mesh-device: TG,
-          #   override-tt-config: "{\"data_parallel\": 16, \"fabric_config\": \"FABRIC_1D_RING\"}",
-          #   tt-llama-text-ver: tt_transformers,
-          #   multimodal: false,
-          #   co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
-          #   co-owner-2-id: U08BH66EXAL, # Radoica Draskic
-          # },
-          # {
-          #   name: "[WH-T3K] Gemma3-27B",
-          #   model: "google/gemma-3-27b-it",
-          #   server-timeout: 10,
-          #   benchmark-timeout: 5,
-          #   runner-label: config-t3000,
-          #   mesh-device: T3K,
-          #   override-tt-config: "{\"fabric_config\": \"FABRIC_1D\", \"l1_small_size\": 768}",
-          #   tt-llama-text-ver: tt_transformers,
-          #   multimodal: false, # Disabled until the error seen in https://github.com/tenstorrent/tt-metal/actions/runs/18021096729/job/51279632451 is fixed
-          #   co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
-          #   co-owner-2-id: U08BH66EXAL, # Radoica Draskic
-          # },
+          {
+            name: "[BH-DB] Llama-3.1-8B-Instruct",
+            model: "meta-llama/Llama-3.1-8B-Instruct",
+            server-timeout: 5,
+            benchmark-timeout: 5,
+            runner-label: BH-DeskBox,
+            mesh-device: P150x2,
+            tt-llama-text-ver: tt_transformers,
+            override-tt-config: "{\"data_parallel\": 2}",
+            multimodal: false,
+            owner_id: U08GELBB1AP, # Ambrose Ling
+          },
+          {
+            name: "[BH-QB] Llama-3.1-8B-Instruct",
+            model: "meta-llama/Llama-3.1-8B-Instruct",
+            server-timeout: 5,
+            benchmark-timeout: 5,
+            runner-label: bh-LLMBox,
+            mesh-device: P150x4,
+            tt-llama-text-ver: tt_transformers,
+            override-tt-config: "{\"data_parallel\": 4}",
+            multimodal: false,
+            owner_id: U08CEGF78ET, # Salar Hosseini Khorasgani
+          },
+          {
+            name: "[BH-LB] Llama-3.1-8B-Instruct",
+            model: "meta-llama/Llama-3.1-8B-Instruct",
+            server-timeout: 35,
+            benchmark-timeout: 10,
+            runner-label: bh-rackbox,
+            mesh-device: P150x8,
+            tt-llama-text-ver: tt_transformers,
+            override-tt-config: "{\"data_parallel\": 8}",
+            multimodal: false,
+            owner_id: U08GELBB1AP, # Ambrose Ling
+          },
+          {
+            name: "[WH-GLX] Llama-3.3-70B-Instruct",
+            model: "meta-llama/Llama-3.3-70B-Instruct",
+            server-timeout: 35,
+            benchmark-timeout: 10,
+            runner-label: topology-6u,
+            mesh-device: TG,
+            tt-llama-text-ver: llama3_70b_galaxy,
+            override-tt-config: "{\"dispatch_core_axis\": \"col\", \"sample_on_device_mode\": \"all\", \"fabric_config\": \"FABRIC_1D_RING\", \"worker_l1_size\": 1344544, \"trace_region_size\": 95693824}",
+            multimodal: false,
+            co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
+            co-owner-2-id: U08CEGF78ET, # Salar Hosseini Khorasgani
+          },
+          {
+            name: "[WH-GLX] Llama-8B DP=16",
+            model: "meta-llama/Llama-3.1-8B-Instruct",
+            server-timeout: 10,
+            benchmark-timeout: 5,
+            runner-label: topology-6u,
+            mesh-device: TG,
+            override-tt-config: "{\"data_parallel\": 16, \"fabric_config\": \"FABRIC_1D_RING\"}",
+            tt-llama-text-ver: tt_transformers,
+            multimodal: false,
+            co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
+            co-owner-2-id: U08BH66EXAL, # Radoica Draskic
+          },
+          {
+            name: "[WH-T3K] Gemma3-27B",
+            model: "google/gemma-3-27b-it",
+            server-timeout: 10,
+            benchmark-timeout: 5,
+            runner-label: config-t3000,
+            mesh-device: T3K,
+            override-tt-config: "{\"fabric_config\": \"FABRIC_1D\", \"l1_small_size\": 768}",
+            tt-llama-text-ver: tt_transformers,
+            multimodal: false, # Disabled until the error seen in https://github.com/tenstorrent/tt-metal/actions/runs/18021096729/job/51279632451 is fixed
+            co-owner-1-id: U08E1JCDVNX, # Pavle Petrovic
+            co-owner-2-id: U08BH66EXAL, # Radoica Draskic
+          },
         ]
     runs-on:
       - ${{ matrix.test-group.runner-label }}
@@ -235,30 +235,30 @@ jobs:
           echo "Check out the server log in a step below."
           exit 1
 
-      # - name: 📐 Run benchmark
-      #   timeout-minutes: ${{ matrix.test-group.benchmark-timeout }}
-      #   run: |
-      #     python3 vllm/benchmarks/benchmark_serving.py \
-      #       --backend vllm \
-      #       --model ${{ matrix.test-group.model }} \
-      #       --dataset-name random \
-      #       --num-prompts 32 \
-      #       --random-input-len 100 \
-      #       --random-output-len 100 \
-      #       --ignore-eos \
-      #       --percentile-metrics ttft,tpot,itl,e2el \
-      #       --save-result \
-      #       --result-filename output/vllm_result.json \
-      #       2>&1 | tee ${FILE_BENCHMARK_LOG}
+      - name: 📐 Run benchmark
+        timeout-minutes: ${{ matrix.test-group.benchmark-timeout }}
+        run: |
+          python3 vllm/benchmarks/benchmark_serving.py \
+            --backend vllm \
+            --model ${{ matrix.test-group.model }} \
+            --dataset-name random \
+            --num-prompts 32 \
+            --random-input-len 100 \
+            --random-output-len 100 \
+            --ignore-eos \
+            --percentile-metrics ttft,tpot,itl,e2el \
+            --save-result \
+            --result-filename output/vllm_result.json \
+            2>&1 | tee ${FILE_BENCHMARK_LOG}
 
-      #     # If the backend fails, the benchmark will still complete successfully but with all-zero results.
-      #     # It will contain a warning message, though
-      #     warning_message="All requests failed"
-      #     if grep -q "$warning_message" "${FILE_BENCHMARK_LOG}"; then
-      #       echo "❌ All requests failed"
-      #       echo "Check out the server log in a step below."
-      #       exit 1
-      #     fi
+          # If the backend fails, the benchmark will still complete successfully but with all-zero results.
+          # It will contain a warning message, though
+          warning_message="All requests failed"
+          if grep -q "$warning_message" "${FILE_BENCHMARK_LOG}"; then
+            echo "❌ All requests failed"
+            echo "Check out the server log in a step below."
+            exit 1
+          fi
 
       - name: 🖼️ Run multimodal benchmark
         if: ${{ matrix.test-group.multimodal }}
